### PR TITLE
Add CRUD functionality for Course's API endpoints

### PR DESCRIPTION
**Pull request by philectron**
TODOs:

- [ ] Authentication for routes that require it.
- [ ] The remaining requests which involve foreign keys: GET/POST Course's Students, GET Course's Assignments and Roster).
- [x] Add an extra table to deal with the many-to-many relationship between `Course` and `Student`.

Although this is a work in progress, the APIs for CRUD functionality of the `Course` entity is a major development and is pull-request worthy

### CODE REVIEW

**Review by thegrims — COMMENTED** [review]
I would prefer no changes to the auth variable names, I feel like it might create breaking changes in other parts of the codebase

**Comment by philectron** [comment]
> 
> 
> I would prefer no changes to the auth variable names, I feel like it might create breaking changes in other parts of the codebase

@khashf requested that we need to change the variable name. `req.user` seems a little confusing. I think changing it to `req.authenticatedUserId` is a good idea.

**Review by thegrims — COMMENTED** [review]
rest looks good to me

**Review by thegrims — APPROVED** [review]

**Comment by thegrims** [comment]
> > I would prefer no changes to the auth variable names, I feel like it might create breaking changes in other parts of the codebase
> 
> @khashf requested that we need to change the variable name. `req.user` seems a little confusing. I think changing it to `req.authenticatedUserId` is a good idea.

Fair enough

**Pull request merged**
